/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 3 août 2013, 01:42:23
 */
package main;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JToolBar;

/**
 *
 * @author slouma
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar("Toolbar", JToolBar.HORIZONTAL);
        moi = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        appel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        clavier = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fichier = new javax.swing.JMenu();
        ajoutCompte = new javax.swing.JMenuItem();
        ajoutContact = new javax.swing.JMenuItem();
        creeGroupe = new javax.swing.JMenuItem();
        joinSalon = new javax.swing.JMenuItem();
        Salon = new javax.swing.JMenuItem();
        options = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        sonOff = new javax.swing.JMenuItem();
        sniff = new javax.swing.JMenuItem();
        aide = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

         getContentPane().setBackground(Color.lightGray);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
       // JPanel panel = new JPanel();
       // panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        ImageIcon newi = new ImageIcon(
                getClass().getResource("icon/new.png"));
        ImageIcon delete = new ImageIcon(
                getClass().getResource("icon/Delete.png"));
        ImageIcon open = new ImageIcon(
                getClass().getResource("icon/open.png"));
        ImageIcon save = new ImageIcon(
                getClass().getResource("icon/save.png"));
        ImageIcon exit = new ImageIcon(
                getClass().getResource("icon/exit.png")); 
        ImageIcon house = new ImageIcon(
                getClass().getResource("icon/House.png")); 
        ImageIcon edit = new ImageIcon(
                getClass().getResource("icon/Edit.png")); 
        ImageIcon search = new ImageIcon(
                getClass().getResource("icon/Search.png")); 
        ImageIcon warning = new ImageIcon(
                getClass().getResource("icon/Warning.png")); 
        JButton newb = new JButton(newi);
        JButton deleteb = new JButton(delete);
        JButton openb = new JButton(open);
        JButton saveb = new JButton(save);
        JButton exitb = new JButton(exit);
        JButton editb = new JButton(edit);
        JButton warningb = new JButton(warning);
        JButton searchb = new JButton(search);
        JButton houseb = new JButton(house);
        
        jToolBar1.add(newb);
        jToolBar1.addSeparator();
        jToolBar1.add(openb);
        jToolBar1.addSeparator();
        jToolBar1.add(saveb);
        jToolBar1.addSeparator();
        jToolBar1.add(houseb);
        jToolBar1.addSeparator();
        jToolBar1.add(editb);
        jToolBar1.addSeparator();
        jToolBar1.add(searchb);
        jToolBar1.addSeparator();
        jToolBar1.add(deleteb);
        jToolBar1.addSeparator();
        jToolBar1.add(exitb);
        jToolBar1.addSeparator();
        jToolBar1.add(warningb);
        jToolBar1.setAlignmentX(0);
       // panel.add( jToolBar1);
       // add(panel, BorderLayout.NORTH);

        exitb.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                System.exit(0);
            }

        });

      jToolBar1.setRollover(true);
      try {
          Image img = ImageIO.read(getClass().getResource("icon/users.png"));
          moi.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
        }
        //moi.setText("Moi");

     jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "connecté", "déconnecté" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jTextField1.setText("saisir numéro");
        try {
            Image img = ImageIO.read(getClass().getResource("icon/phone1.png"));
            appel.setIcon(new ImageIcon(img));
          } catch (IOException ex) {
          }
        //appel.setText("Appel");
        appel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appelMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        try {
          Image img = ImageIO.read(getClass().getResource("icon/phone.png"));
          clavier.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
        }
        //clavier.setText("jButton3");
        clavier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clavierMouseClicked(evt);
            }
        });

        fichier.setText("fichier");

        ajoutCompte.setText("ajouter compte");
        ajoutCompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutCompteMouseClicked(evt);
            }
        });
        fichier.add(ajoutCompte);

        ajoutContact.setText("ajouter contact");
        ajoutContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutContactMouseClicked(evt);
            }
        });
        fichier.add(ajoutContact);

        creeGroupe.setText("crée groupe");
        fichier.add(creeGroupe);

        joinSalon.setText("join salon");
        fichier.add(joinSalon);

        Salon.setText("quitter");
        fichier.add(Salon);

        jMenuBar1.add(fichier);

        options.setText("outils");

        jMenuItem6.setText("options");
        options.add(jMenuItem6);

        sonOff.setText("désactiver son");
        options.add(sonOff);

        sniff.setText("sniff");
        options.add(sniff);

        jMenuBar1.add(options);

        aide.setText("aide");

        jMenuItem9.setText("a propos");
        aide.add(jMenuItem9);

        jMenuItem10.setText("mise à jour");
        aide.add(jMenuItem10);

        jMenuBar1.add(aide);

       // setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(clavier)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(appel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, 94, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clavier, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        
        //this.setBackground(Color.blue); 

       pack();
    }// </editor-fold>//GEN-END:initComponents

private void clavierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clavierMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_clavierMouseClicked

private void appelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appelMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_appelMouseClicked

private void ajoutCompteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutCompteMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_ajoutCompteMouseClicked

private void ajoutContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutContactMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_ajoutContactMouseClicked

private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Salon;
    private javax.swing.JMenu aide;
    private javax.swing.JMenuItem ajoutCompte;
    private javax.swing.JMenuItem ajoutContact;
    private javax.swing.JButton appel;
    private javax.swing.JButton clavier;
    private javax.swing.JMenuItem creeGroupe;
    private javax.swing.JMenu fichier;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
   private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem joinSalon;
    private javax.swing.JButton moi;
    private javax.swing.JMenu options;
    private javax.swing.JMenuItem sniff;
    private javax.swing.JMenuItem sonOff;
   // private static final Color moncouleur = new Color(200, 200, 255);
    // End of variables declaration//GEN-END:variables
}
